### ISSUE TITLE
implement toString() in all DTO and POJO

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-library-java-spring#10]
Hello,

could you please implement the toString() method in all DTO and POJO classes. This will decrease debugging time and leads to a better code quality because we don't need to create extra methods or long nested implemenations to get the information from the objects. The GSON library would be a good choice for this purpose, as it can do this quickly and easily. For example:

```java
@Override
public String toString() {
    return new Gson().toJson(this);
}
```

KR,
BlackRose01

**Comment by BlackRose01** [comment]
sorry but bump

**Comment by borditamas** [comment]
Hi,
feel free to create a PR with your changes in core-java-spring repository. (All the DTO comes from the dto package of that repository).

It would be useful indeed, but for us it is not the highest priotity to deal with at the moment.

**Comment by BlackRose01** [comment]
Hello,

I cloned this repository (master) and I cannot find the DTO package.

![image](https://user-images.githubusercontent.com/7542316/90113352-80ba3d80-dd51-11ea-9a44-5472c14c75d5.png)

KR

**Comment by borditamas** [comment]
Hi,

as I wrote all DTO comes from [core-java-spring repository](https://github.com/arrowhead-f/core-java-spring).

**Comment by BlackRose01** [comment]
[Pull Request](https://github.com/arrowhead-f/core-java-spring/pull/259) was created.
