### ISSUE TITLE
improvement/simplification of client-library and client-skeleton

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-library-java-spring#11]
Hello,

please have a look at the following repository. Due to the current implementation of the use cases of the HTW Dresden, I noticed a few anomalies in the current skeleton as well as in the library. For this reason I have adapted the skeleton based on my estimations.

What was adapted:
* The entry 0.0.0.0.0 at server.address is automatically translated into all available IP addresses of the system and entered in the Service Registry
* Classes for the Core Services were created, which can be integrated and used via injection
* The Service Registry injection class can also register providers from other systems
* The behavior of the injection classes for the Orchestrator, Event Handler and the Service Registry can be controlled with defined entries in the application.properties
* The injection classes of the Core Services have setters, with which the transferred entries from the application.properties can be overwritten during runtime
* Each client type has a minimalist example
* The control properties for the injection classes have a common root for Arrowhead (example: arrowhead.client.orchestrator)
* also still other points, which I have forgotten now

[Link to Repository](https://iversion.informatik.htw-dresden.de/smartproductionsystems/projects/arrowhead-tools/improved-client-skeleton)

Kind Regards,
BlackRose01

**Comment by BlackRose01** [comment]
sorry but bump

**Comment by borditamas** [comment]
Hi,
are you willing to contribute to client-library-java-spring project?

    - Clone the repo.
    - Work on your implementation in a new branch. Follow coding conventions!
    - Write tests!
    - Ask pull request.

Br, Tamás

**Comment by BlackRose01** [comment]
Hello,

I cloned the repository but I receive the error "Cannot resolve eu.arrowhead:core-client-skeleton:4.1.3.9".

KR

**Comment by borditamas** [comment]
Did you configure maven to GitHub Packages? Guide is under [Requirements section](https://github.com/arrowhead-f/client-library-java-spring#requirements).

**Comment by BlackRose01** [comment]
I think so but I just merges it with my classes now. The [Pull Request](https://github.com/arrowhead-f/client-library-java-spring/pull/12) was created.
