### ISSUE TITLE
SSLProperties are mandatory in unsecure mode

### ISSUE THREAD

**Issue by marci543** [arrowhead-f/client-library-java-spring#14]
SSLProperties should be wired using `required=false` to avoid the need of defining SSL-related properties in `application.properties` in unsecure mode.
https://github.com/arrowhead-f/client-library-java-spring/blob/e47f6e66734c3def4e8054764693c35de0918af7/src/main/java/eu/arrowhead/client/library/ArrowheadService.java#L74-L75

**Comment by borditamas** [comment]
Secure mode is the forced way of developing Arrowhead complient systems. But if you playing around in unsecure mode you don't have to define the ssl properties, just make sure that `server.ssl.enabled` is set to false.

**Comment by marci543** [comment]
I've set `server.ssl.enabled=false` but I still have to define `server.ssl.*` properties (at least with empty values) otherwise I get this error:

> java.lang.IllegalStateException: Failed to load ApplicationContext
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
> 	...
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'MyApplicationInitListener': Unsatisfied dependency expressed through field 'arrowheadService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ArrowheadService': Unsatisfied dependency expressed through field 'sslProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SSLProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'server.ssl.key-store-type' in value "${server.ssl.key-store-type}"
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
> 	...
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: **Error creating bean with name 'ArrowheadService': Unsatisfied dependency expressed through field 'sslProperties';** nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SSLProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'server.ssl.key-store-type' in value "${server.ssl.key-store-type}"
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
> 	...
> Caused by: org.springframework.beans.factory.BeanCreationException: **Error creating bean with name 'SSLProperties':** Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'server.ssl.key-store-type' in value "${server.ssl.key-store-type}"
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405)
> 	...
> Caused by: java.lang.IllegalArgumentException: **Could not resolve placeholder 'server.ssl.key-store-type' in value "${server.ssl.key-store-type}"**
> 	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)
> 	...

**Comment by borditamas** [comment]
I have tried out it with the current [demo-car-provider](https://github.com/arrowhead-f/sos-examples-spring/tree/master/demo-car) which is using the latest client-library (4.1.3.13), but couldn't duplicate your issue.
When the values are not defined then the variables will be empty strings and null values.
![image](https://user-images.githubusercontent.com/48867251/112045086-bd9dac80-8b4a-11eb-927a-1f04b0af011b.png)
I could run it also from terminal without any error even if I delete all the server.ssl.* keys from the property file.

Which spring verison are you using in your project?
Are you using multiple property sources or only the application.properties file?

**Comment by marci543** [comment]
There wasn't any problem in case of empty properties for me either.

I reproduced the problem here: https://github.com/marci543/sos-examples-spring/commit/d74ea8026bf7e125e54958380fdb3599445ee8ef
With empty properties the provider starts (and tries to connect to Service Registry): https://github.com/marci543/sos-examples-spring/actions/runs/681050480
With the properties removed it fails to start because `SSLProperties` are auto-wired using the default `required=true`: https://github.com/marci543/sos-examples-spring/actions/runs/681059360

**Comment by borditamas** [comment]
Okay, I see now why it worked for me with removed properties. I have removed them only from the prop file copied next to the executable jar, but not removed from file built into the jar.

So, the thing is that this class is coming directly from [core-common](https://github.com/eclipse-arrowhead/core-java-spring/tree/master/core-common) module as a transitive dependency, therefore I will redirect this issue there. 

Using `required=false` is not a good approach I think. We still expect to this bean is not null in many cases, so I would rather use empty strings as declared default values for its members.

Thanks for reporting this incompleteness!
