### ISSUE TITLE
Orchestration/Service Registration not meaningful for server.address 0.0.0.0

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-library-java-spring#30]
Hello,

currently I try to orchestrate some services and I found a problem there in combination with the service registry registering process. In Spring we can enter the value "0.0.0.0" for the option `server.address` which means that our application listen on all available network devices. For this scenario it is meaningful to substitute this address to all available network addresses from the system and register them all. Also the orchestrator method has the same implementation and tries to request the orchestrator with the system address "0.0.0.0".

```java
    /**
     * return all interface addresses from all NICs of the client
     * @return
     * @throws SocketException
     */
    public static List<InetAddress> getInetAddressesFromNics() throws SocketException {
        List<InetAddress> addrList = new ArrayList<InetAddress>();

        // iterate through all NIC interfaces
        for(Enumeration<NetworkInterface> eni = NetworkInterface.getNetworkInterfaces(); eni.hasMoreElements(); ) {
            final NetworkInterface ifc = eni.nextElement();

            // ignore loopback and down interfaces
            if(ifc.isUp() && !ifc.isLoopback()) {
                // iterate throw all addresses of interfaces
                for (Enumeration<InetAddress> ena = ifc.getInetAddresses(); ena.hasMoreElements(); ) {
                    InetAddress addr = ena.nextElement();

                    // ignore linklocal and 169.x.x.x addresses
                    if (!addr.isLinkLocalAddress() && !addr.getHostAddress().matches("169.[0-9]+.[0-9]+.[0-9]+"))
                        addrList.add(addr);
                }
            }
        }

        return addrList;
    }
```

KR,
BlackRose01

**Comment by borditamas** [comment]
Hello,

personally I don't think that it would be a good approach. When SSL is enabled, than it would mean that every possible ip address need to be included by the certificate as Subject Alternative Name.

When SSL is disabled than the Core Systems 4.4 release candidate offers the network address detection feature.

see:
https://github.com/eclipse-arrowhead/core-java-spring/issues/265
https://github.com/eclipse-arrowhead/core-java-spring/issues/222
https://github.com/eclipse-arrowhead/core-java-spring/issues/309 

BR,
Tamás

**Comment by BlackRose01** [comment]
But is it possible to say that in secure mode only ip addresses will be registered which are listed in the certificate?

**Comment by borditamas** [comment]
I suppose technically it would be resoluble, but don't understand why you could not set the ip in config file while you did set in the certificate. Besides on this from ServiceRegistry perspective it would appear as more individual system, which is not case.

**Comment by BlackRose01** [comment]
Sorry for the late answer but the notification system don't send me any notifications.
I think the biggest problem here is the Docker part because when I create a docker container then the ip address will be managed via the docker system normally.

**Comment by borditamas** [comment]
That's why we have `domain.name` property in the config file.  I think you should use that similarly like the core systems are using it in a docker environment.
