### ISSUE TITLE
Arrowhead configuration parameters according to Spring configuration in application.properties

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-library-java-spring#8]
Hey there,

it would be within the realm of possibility that the Arrowhead configuration parameters in the application.properties could have the same structure as Spring's default parameters. On the one hand, this would improve the overview and the parameters would be more logical, since they have a tree structure. It is also very helpful for documentations. As an example I could imagine the following:

arrowhead.client.service_registry = 127.0.0.1
arrowhead.clien.consumer.name = CONSUMER

It would be nice to see if you can implement this in the core services too.

arrowhead.core.name = SERVICE_REGISTRY
arrowhead.core.service_registry.ping_scheduled = false

Cheers,
BlackRose01

**Comment by MaGaMeGa** [comment]
@BlackRose01 
There are pros and cons to differentiate the custom property names or use them as Spring's default parameters. It may worth a discussion during the planning of the next version of Arrowhead Core Systems. As far as I'm aware, there are no plans to change the property names in the current version.
In the meantime, please do feel free to name the parameters of your client applications, as you like.

**Comment by BlackRose01** [comment]
That's great. The planning or the attempt to implement it in the next version is already sufficient.
