### ISSUE TITLE
automatic system registration for consumer

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-library-java-spring#9]
Hello there,

could a method be implemented in the Service Registry that automatically registers the consumer? However, the consumer should not be written directly to the system_ table but to a temporary system_ table.  An explanatory text can be sent with the consumer. The procedure is similar to that for sharepoint when you create a permission request for a page. The activation is then carried out by an administrator. If this is approved, the system ends up in the system_ table. If it is rejected, the system is deleted. Systems that have not been processed after x days are automatically deleted from the table. Analogously, this could also be implemented for service authorizations (intra/inter cloud rules).

This is intended to make the process more independent and secure, since not every user should and may unlock systems on his or her own. This should also reduce the probability of errors during information transfer.

Kind regards,
BlackRose01

**Comment by tsvetlin** [comment]
Hello!

The onboarding does this :) 

Best wishes,
Svetlin

**Comment by BlackRose01** [comment]
In the context of the framework, what is onboarding?

**Comment by tsvetlin** [comment]
https://ieeexplore.ieee.org/document/8390800

**Comment by BlackRose01** [comment]
Thank you :)
